### ISSUE TITLE
Action: "Restart kernel" in github codespaces seems not to work 

### ISSUE THREAD

**Issue by bmerkle** [githubnext/vitale#52]
I am using the samples of vitale in github codespaces.
Executing the e.g. azure-ai.vnb runs fine.

However if i use "Restart kernel" then the notebook becomes unusable, seems to be an endless loop.

Please see screenshot attached.
![image](https://github.com/user-attachments/assets/fce8ecab-0676-4a6a-873a-19d9f444651d)

**Comment by jaked** [comment]
thanks for the report! I'll take a look.

**Comment by jaked** [comment]
fixed in https://github.com/githubnext/vitale/commit/f3d9d4fc22823d62341491acabbfb72fceec47f4
