### ISSUE TITLE
Support for npm package installation in notebook

### ISSUE THREAD

**Issue by bmerkle** [githubnext/vitale#53]
In jupter I can install a python package within the  notebook via
%pip install <packagename>

I tried the same with npm in vitale but it seem not to be supported
%npm install <packagename> 
results in a syntax error

I tried both with ! and % (while % is the recommended way in jupyter)

![image](https://github.com/user-attachments/assets/79cbb2ba-e11e-42ae-b7f8-17686a216a53)

**Comment by jaked** [comment]
thanks for the report!

Vitale doesn't support in-notebook syntax for installing packages, but Vitale notebooks can use packages installed the usual way (via `package.json` / `node_modules`).

**Comment by bmerkle** [comment]
installing is performed the usual npm way, makes sense :-)
